import datetime
from suntime import Sun, SunTimeException

latitude = 39.653948
longitude = -104.879104

sun = Sun(latitude, longitude)

today_sunset = sun.get_local_sunset_time()
#print(type(today_sunset.hour))
with open("sunset_time.txt", 'w') as file:
    file.write(f'{today_sunset.hour}'.zfill(2) + ":" + f'{today_sunset.minute}'.zfill(2))
    
with open("crontab_root_copy", 'w') as file:
    file.write("# DO NOT EDIT THIS FILE - edit the master and reinstall.\n\
# (/tmp/crontab.W7dKWm/crontab installed on Mon Jan  2 22:36:14 2023)\n\
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)\n\
# Edit this file to introduce tasks to be run by cron.\n\
#\n\
# Each task to run has to be defined through a single line\n\
# indicating with different fields when the task will be run\n\
# and what command to run for the task\n\
#\n\
# To define the time you can provide concrete values for\n\
# minute (m), hour (h), day of month (dom), month (mon),\n\
# and day of week (dow) or use '*' in these fields (for 'any').\n\
#\n\
# Notice that tasks will be started based on the cron's system\n\
# daemon's notion of time and timezones.\n\
#\n\
# Output of the crontab jobs (including errors) is sent through\n\
# email to the user the crontab file belongs to (unless redirected).\n\
#\n\
# For example, you can run a backup of all your user accounts\n\
# at 5 a.m every week with:\n\
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/\n\
#\n\
# For more information see the manual pages of crontab(5) and cron(8)\n\
#\n\
# m h  dom mon dow   command\n\
#*/2 * * * * sudo killall python ; sudo /usr/bin/python /home/peter/LED_CODE/WS2812LED_PythonCode/CornellCollegeColors.py\n\
#1-59/2 * * * * sudo killall python ; sudo /usr/bin/python /home/peter/LED_CODE/WS2812LED_PythonCode/UniversityOfIowaColors.py\n\
" + f'{today_sunset.minute}'.zfill(2) + " " + f'{today_sunset.hour}'.zfill(2) + " * * * sudo killall python ; sudo /usr/bin/python /home/peter/LED_CODE/WS2812LED_PythonCode/slow_change.py\n\
0 22 * * * sudo killall python\n\
55 11 * * * sudo killall python ; sudo /usr/bin/python /home/peter/LED_CODE/WS2812LED_PythonCode/sunset.py\n\
0 12 * * * sudo cp /home/peter/LED_CODE/WS2812LED_PythonCode/crontab_root_copy /var/spool/cron/crontabs/root\n\
")